declare namespace NodeJS {
  export interface ProcessEnv {
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    UPSTASH_REDIS_REST_URL: string;
    UPSTASH_REDIS_REST_TOKEN: string;
    NEXTAUTH_URL: string;
    NEXTAUTH_SECRET: string;
    NEXT_PUBLIC_UPSTASH_REDIS_REST_URL: string;
    NEXT_PUBLIC_UPSTASH_REDIS_REST_TOKEN: string;
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: string;
    NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: string;
    NEXT_PUBLIC_NEXT_PUBLIC_UPSTASH_REDIS_REST_URL: string;
    NEXT_PUBLIC_NEXT_PUBLIC_UPSTASH_REDIS_REST_TOKEN: string;
    NEXT_PUBLIC_NEXT_PUBLIC_GOOGLE_CLIENT_ID: string;
  }
}
